package com.tomas.mybatis.model;

import org.mybatis.cdi.Mapper;

import java.util.Date;


public class Battle {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATTLE.ID
     *
     * @mbg.generated Mon Apr 19 13:41:06 EEST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATTLE.CREATIONDATE
     *
     * @mbg.generated Mon Apr 19 13:41:06 EEST 2021
     */
    private Date creationdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATTLE.NAME
     *
     * @mbg.generated Mon Apr 19 13:41:06 EEST 2021
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATTLE.ID
     *
     * @return the value of BATTLE.ID
     *
     * @mbg.generated Mon Apr 19 13:41:06 EEST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATTLE.ID
     *
     * @param id the value for BATTLE.ID
     *
     * @mbg.generated Mon Apr 19 13:41:06 EEST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATTLE.CREATIONDATE
     *
     * @return the value of BATTLE.CREATIONDATE
     *
     * @mbg.generated Mon Apr 19 13:41:06 EEST 2021
     */
    public Date getCreationdate() {
        return creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATTLE.CREATIONDATE
     *
     * @param creationdate the value for BATTLE.CREATIONDATE
     *
     * @mbg.generated Mon Apr 19 13:41:06 EEST 2021
     */
    public void setCreationdate(Date creationdate) {
        this.creationdate = creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATTLE.NAME
     *
     * @return the value of BATTLE.NAME
     *
     * @mbg.generated Mon Apr 19 13:41:06 EEST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATTLE.NAME
     *
     * @param name the value for BATTLE.NAME
     *
     * @mbg.generated Mon Apr 19 13:41:06 EEST 2021
     */
    public void setName(String name) {
        this.name = name;
    }
}