package com.tomas.mybatis.model;

import org.mybatis.cdi.Mapper;


public class Samurai {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SAMURAI.ID
     *
     * @mbg.generated Mon Apr 19 13:41:06 EEST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SAMURAI.NAME
     *
     * @mbg.generated Mon Apr 19 13:41:06 EEST 2021
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SAMURAI.ID
     *
     * @return the value of SAMURAI.ID
     *
     * @mbg.generated Mon Apr 19 13:41:06 EEST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SAMURAI.ID
     *
     * @param id the value for SAMURAI.ID
     *
     * @mbg.generated Mon Apr 19 13:41:06 EEST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SAMURAI.NAME
     *
     * @return the value of SAMURAI.NAME
     *
     * @mbg.generated Mon Apr 19 13:41:06 EEST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SAMURAI.NAME
     *
     * @param name the value for SAMURAI.NAME
     *
     * @mbg.generated Mon Apr 19 13:41:06 EEST 2021
     */
    public void setName(String name) {
        this.name = name;
    }
}