package com.tomas.mybatis.dao;

import com.tomas.mybatis.model.Battle;
import java.util.List;

public interface BattleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BATTLE
     *
     * @mbg.generated Mon Apr 19 12:02:24 EEST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BATTLE
     *
     * @mbg.generated Mon Apr 19 12:02:24 EEST 2021
     */
    int insert(Battle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BATTLE
     *
     * @mbg.generated Mon Apr 19 12:02:24 EEST 2021
     */
    Battle selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BATTLE
     *
     * @mbg.generated Mon Apr 19 12:02:24 EEST 2021
     */
    List<Battle> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BATTLE
     *
     * @mbg.generated Mon Apr 19 12:02:24 EEST 2021
     */
    int updateByPrimaryKey(Battle record);
}