package com.tomas.mybatis.dao;

import com.tomas.mybatis.model.SamuraiQuote;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface SamuraiQuoteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAMURAIQUOTE
     *
     * @mbg.generated Mon Apr 19 13:41:06 EEST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAMURAIQUOTE
     *
     * @mbg.generated Mon Apr 19 13:41:06 EEST 2021
     */
    int insert(SamuraiQuote record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAMURAIQUOTE
     *
     * @mbg.generated Mon Apr 19 13:41:06 EEST 2021
     */
    SamuraiQuote selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAMURAIQUOTE
     *
     * @mbg.generated Mon Apr 19 13:41:06 EEST 2021
     */
    List<SamuraiQuote> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAMURAIQUOTE
     *
     * @mbg.generated Mon Apr 19 13:41:06 EEST 2021
     */
    int updateByPrimaryKey(SamuraiQuote record);
}