package com.tomas.mybatis.dao;

import com.tomas.mybatis.model.Samurai;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface SamuraiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAMURAI
     *
     * @mbg.generated Mon Apr 19 13:41:06 EEST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAMURAI
     *
     * @mbg.generated Mon Apr 19 13:41:06 EEST 2021
     */
    int insert(Samurai record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAMURAI
     *
     * @mbg.generated Mon Apr 19 13:41:06 EEST 2021
     */
    Samurai selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAMURAI
     *
     * @mbg.generated Mon Apr 19 13:41:06 EEST 2021
     */
    List<Samurai> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAMURAI
     *
     * @mbg.generated Mon Apr 19 13:41:06 EEST 2021
     */
    int updateByPrimaryKey(Samurai record);
}