package com.tomas.mybatis.dao;

import com.tomas.mybatis.model.Samuraiquote;
import java.util.List;

public interface SamuraiquoteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAMURAIQUOTE
     *
     * @mbg.generated Mon Apr 19 12:02:24 EEST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAMURAIQUOTE
     *
     * @mbg.generated Mon Apr 19 12:02:24 EEST 2021
     */
    int insert(Samuraiquote record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAMURAIQUOTE
     *
     * @mbg.generated Mon Apr 19 12:02:24 EEST 2021
     */
    Samuraiquote selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAMURAIQUOTE
     *
     * @mbg.generated Mon Apr 19 12:02:24 EEST 2021
     */
    List<Samuraiquote> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAMURAIQUOTE
     *
     * @mbg.generated Mon Apr 19 12:02:24 EEST 2021
     */
    int updateByPrimaryKey(Samuraiquote record);
}